server:
  port: 8888
spring:
  jackson:
    date-format: yyyy-MM-dd
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    name: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml



resource:
  imagesServer: http://images.pyg.com
  emailServer: http://emails.pyg.com


